import java.util.*;

import javax.swing.*;

public class CheckM extends Material{
	ArrayList<String> mat= new ArrayList<String>();;
	public void Check채소_과일(JCheckBox checkBox, JCheckBox checkBox_1, JCheckBox checkBox_2, JCheckBox checkBox_3, JCheckBox checkBox_4, JCheckBox checkBox_5, JCheckBox checkBox_6, JCheckBox checkBox_7, JCheckBox checkBox_8, JCheckBox checkBox_9, JCheckBox checkBox_10, JCheckBox checkBox_11, JCheckBox checkBox_12, JCheckBox checkBox_13, JCheckBox checkBox_14, JCheckBox checkBox_15, JCheckBox checkBox_16, JCheckBox checkBox_17, JCheckBox checkBox_18, JCheckBox checkBox_19, JCheckBox checkBox_20, JCheckBox checkBox_21, JCheckBox checkBox_22, JCheckBox checkBox_23, JCheckBox checkBox_24, JCheckBox checkBox_25, JCheckBox checkBox_26, JCheckBox checkBox_27, JCheckBox checkBox_28, JCheckBox checkBox_29, JCheckBox checkBox_30, JCheckBox checkBox_31, JCheckBox checkBox_32, JCheckBox checkBox_33, JCheckBox checkBox_34, JCheckBox checkBox_35, JCheckBox checkBox_36, JCheckBox checkBox_37, JCheckBox checkBox_38, JCheckBox checkBox_39, JCheckBox checkBox_40, JCheckBox checkBox_41, JCheckBox checkBox_42, JCheckBox checkBox_43, JCheckBox checkBox_44, JCheckBox checkBox_45)
	{
		if(checkBox.isSelected())
		{
			mat.add(checkBox.getText());
		}
		if(checkBox_1.isSelected())
		{
			mat.add(checkBox_1.getText());
		}
		if(checkBox_2.isSelected())
		{
			mat.add(checkBox_2.getText());
		}
		if(checkBox_3.isSelected())
		{
			mat.add(checkBox_3.getText());
		}
		if(checkBox_4.isSelected())
		{
			mat.add(checkBox_4.getText());
		}
		if(checkBox_5.isSelected())
		{
			mat.add(checkBox_5.getText());
		}
		if(checkBox_6.isSelected())
		{
			mat.add(checkBox_6.getText());
		}
		if(checkBox_7.isSelected())
		{
			mat.add(checkBox_7.getText());
		}
		if(checkBox_8.isSelected())
		{
			mat.add(checkBox_8.getText());
		}
		if(checkBox_9.isSelected())
		{
			mat.add(checkBox_9.getText());
		}
		if(checkBox_10.isSelected())
		{
			mat.add(checkBox_10.getText());
		}
		if(checkBox_11.isSelected())
		{
			mat.add(checkBox_11.getText());
		}
		if(checkBox_12.isSelected())
		{
			mat.add(checkBox_12.getText());
		}
		if(checkBox_13.isSelected())
		{
			mat.add(checkBox_13.getText());
		}
		
		if(checkBox_14.isSelected())
		{
			mat.add(checkBox_14.getText());
		}
		if(checkBox_15.isSelected())
		{
			mat.add(checkBox_15.getText());
		}		
		if(checkBox_16.isSelected())
		{
			mat.add(checkBox_16.getText());
		}
		if(checkBox_17.isSelected())
		{
			mat.add(checkBox_17.getText());
		}
		if(checkBox_18.isSelected())
		{
			mat.add(checkBox_18.getText());
		}
		if(checkBox_19.isSelected())
		{
			mat.add(checkBox_19.getText());
		}
		if(checkBox_20.isSelected())
		{
			mat.add(checkBox_20.getText());
		}
		if(checkBox_21.isSelected())
		{
			mat.add(checkBox_21.getText());
		}
		if(checkBox_22.isSelected())
		{
			mat.add(checkBox_22.getText());
		}
		if(checkBox_23.isSelected())
		{
			mat.add(checkBox_23.getText());
		}
		if(checkBox_24.isSelected())
		{
			mat.add(checkBox_24.getText());
		}
		if(checkBox_25.isSelected())
		{
			mat.add(checkBox_25.getText());
		}
		if(checkBox_26.isSelected())
		{
			mat.add(checkBox_26.getText());
		}
		if(checkBox_27.isSelected())
		{
			mat.add(checkBox_27.getText());
		}
		if(checkBox_28.isSelected())
		{
			mat.add(checkBox_28.getText());
		}
		if(checkBox_29.isSelected())
		{
			mat.add(checkBox_29.getText());
		}
		if(checkBox_30.isSelected())
		{
			mat.add(checkBox_30.getText());
		}
		if(checkBox_31.isSelected())
		{
			mat.add(checkBox_31.getText());
		}
		if(checkBox_32.isSelected())
		{
			mat.add(checkBox_32.getText());
		}
		if(checkBox_33.isSelected())
		{
			mat.add(checkBox_33.getText());
		}
		if(checkBox_34.isSelected())
		{
			mat.add(checkBox_34.getText());
		}
		if(checkBox_35.isSelected())
		{
			mat.add(checkBox_35.getText());
		}
		if(checkBox_36.isSelected())
		{
			mat.add(checkBox_36.getText());
		}
		if(checkBox_37.isSelected())
		{
			mat.add(checkBox_37.getText());
		}
		if(checkBox_38.isSelected())
		{
			mat.add(checkBox_38.getText());
		}
		if(checkBox_39.isSelected())
		{
			mat.add(checkBox_39.getText());
		}
		if(checkBox_40.isSelected())
		{
			mat.add(checkBox_40.getText());
		}
		if(checkBox_41.isSelected())
		{
			mat.add(checkBox_41.getText());
		}
		if(checkBox_42.isSelected())
		{
			mat.add(checkBox_42.getText());
		}
		if(checkBox_43.isSelected())
		{
			mat.add(checkBox_43.getText());
		}
		if(checkBox_44.isSelected())
		{
			mat.add(checkBox_44.getText());
		}
		if(checkBox_45.isSelected())
		{
			mat.add(checkBox_45.getText());
		}
		System.out.println(mat);
		setMat(mat);
	}
	public void Check육류(JCheckBox checkBox, JCheckBox checkBox_1, JCheckBox checkBox_2, JCheckBox checkBox_3, JCheckBox checkBox_4, JCheckBox checkBox_5)
	{
		if(checkBox.isSelected())
		{
			mat.add(checkBox.getText());
		}
		if(checkBox_1.isSelected())
		{
			mat.add(checkBox_1.getText());
		}
		if(checkBox_2.isSelected())
		{
			mat.add(checkBox_2.getText());
		}
		if(checkBox_3.isSelected())
		{
			mat.add(checkBox_3.getText());
		}
		if(checkBox_4.isSelected())
		{
			mat.add(checkBox_4.getText());
		}
		if(checkBox_5.isSelected())
		{
			mat.add(checkBox_5.getText());
		}
		System.out.println(mat);
		setMat(mat);
	}
	public void Check양념_소스(JCheckBox checkBox, JCheckBox checkBox_1, JCheckBox checkBox_2, JCheckBox checkBox_3, JCheckBox checkBox_4, JCheckBox checkBox_5, JCheckBox checkBox_6, JCheckBox checkBox_7, JCheckBox checkBox_8, JCheckBox checkBox_9, JCheckBox checkBox_10, JCheckBox checkBox_11, JCheckBox checkBox_12, JCheckBox checkBox_13, JCheckBox checkBox_14, JCheckBox checkBox_15, JCheckBox checkBox_16, JCheckBox checkBox_17, JCheckBox checkBox_18, JCheckBox checkBox_19, JCheckBox checkBox_20, JCheckBox checkBox_21, JCheckBox checkBox_22, JCheckBox checkBox_23, JCheckBox checkBox_24, JCheckBox checkBox_25, JCheckBox checkBox_27)
	{
		if(checkBox.isSelected())
		{
			mat.add(checkBox.getText());
		}
		if(checkBox_1.isSelected())
		{
			mat.add(checkBox_1.getText());
		}
		if(checkBox_2.isSelected())
		{
			mat.add(checkBox_2.getText());
		}
		if(checkBox_3.isSelected())
		{
			mat.add(checkBox_3.getText());
		}
		if(checkBox_4.isSelected())
		{
			mat.add(checkBox_4.getText());
		}
		if(checkBox_5.isSelected())
		{
			mat.add(checkBox_5.getText());
		}
		if(checkBox_6.isSelected())
		{
			mat.add(checkBox_6.getText());
		}
		if(checkBox_7.isSelected())
		{
			mat.add(checkBox_7.getText());
		}
		if(checkBox_8.isSelected())
		{
			mat.add(checkBox_8.getText());
		}
		if(checkBox_9.isSelected())
		{
			mat.add(checkBox_9.getText());
		}
		if(checkBox_10.isSelected())
		{
			mat.add(checkBox_10.getText());
		}
		if(checkBox_11.isSelected())
		{
			mat.add(checkBox_11.getText());
		}
		if(checkBox_12.isSelected())
		{
			mat.add(checkBox_12.getText());
		}
		if(checkBox_13.isSelected())
		{
			mat.add(checkBox_13.getText());
		}
		
		if(checkBox_14.isSelected())
		{
			mat.add(checkBox_14.getText());
		}
		if(checkBox_15.isSelected())
		{
			mat.add(checkBox_15.getText());
		}		
		if(checkBox_16.isSelected())
		{
			mat.add(checkBox_16.getText());
		}
		if(checkBox_17.isSelected())
		{
			mat.add(checkBox_17.getText());
		}
		if(checkBox_18.isSelected())
		{
			mat.add(checkBox_18.getText());
		}
		if(checkBox_19.isSelected())
		{
			mat.add(checkBox_19.getText());
		}
		if(checkBox_20.isSelected())
		{
			mat.add(checkBox_20.getText());
		}
		if(checkBox_21.isSelected())
		{
			mat.add(checkBox_21.getText());
		}
		if(checkBox_22.isSelected())
		{
			mat.add(checkBox_22.getText());
		}
		if(checkBox_23.isSelected())
		{
			mat.add(checkBox_23.getText());
		}
		if(checkBox_24.isSelected())
		{
			mat.add(checkBox_24.getText());
		}
		if(checkBox_25.isSelected())
		{
			mat.add(checkBox_25.getText());
		}
		if(checkBox_27.isSelected())
		{
			mat.add(checkBox_27.getText());
		}
		System.out.println(mat);
		setMat(mat);
	}
	public void Check수산물(JCheckBox checkBox, JCheckBox checkBox_1, JCheckBox checkBox_2, JCheckBox checkBox_3, JCheckBox checkBox_4, JCheckBox checkBox_5, JCheckBox checkBox_6, JCheckBox checkBox_7, JCheckBox checkBox_9, JCheckBox checkBox_10, JCheckBox checkBox_11, JCheckBox checkBox_12, JCheckBox checkBox_13, JCheckBox checkBox_14, JCheckBox checkBox_15, JCheckBox checkBox_16, JCheckBox checkBox_17)
	{
		if(checkBox.isSelected())
		{
			mat.add(checkBox.getText());
		}
		if(checkBox_1.isSelected())
		{
			mat.add(checkBox_1.getText());
		}
		if(checkBox_2.isSelected())
		{
			mat.add(checkBox_2.getText());
		}
		if(checkBox_3.isSelected())
		{
			mat.add(checkBox_3.getText());
		}
		if(checkBox_4.isSelected())
		{
			mat.add(checkBox_4.getText());
		}
		if(checkBox_5.isSelected())
		{
			mat.add(checkBox_5.getText());
		}
		if(checkBox_6.isSelected())
		{
			mat.add(checkBox_6.getText());
		}
		if(checkBox_7.isSelected())
		{
			mat.add(checkBox_7.getText());
		}
		if(checkBox_9.isSelected())
		{
			mat.add(checkBox_9.getText());
		}
		if(checkBox_10.isSelected())
		{
			mat.add(checkBox_10.getText());
		}
		if(checkBox_11.isSelected())
		{
			mat.add(checkBox_11.getText());
		}
		if(checkBox_12.isSelected())
		{
			mat.add(checkBox_12.getText());
		}
		if(checkBox_13.isSelected())
		{
			mat.add(checkBox_13.getText());
		}
		
		if(checkBox_14.isSelected())
		{
			mat.add(checkBox_14.getText());
		}
		if(checkBox_15.isSelected())
		{
			mat.add(checkBox_15.getText());
		}		
		if(checkBox_16.isSelected())
		{
			mat.add(checkBox_16.getText());
		}
		if(checkBox_17.isSelected())
		{
			mat.add(checkBox_17.getText());
		}
		System.out.println(mat);
		setMat(mat);
	}
	public void Check기타(JCheckBox checkBox, JCheckBox checkBox_1, JCheckBox checkBox_2, JCheckBox checkBox_3, JCheckBox checkBox_4, JCheckBox checkBox_5, JCheckBox checkBox_6, JCheckBox checkBox_7, JCheckBox checkBox_8, JCheckBox checkBox_9, JCheckBox checkBox_10, JCheckBox checkBox_11, JCheckBox checkBox_12, JCheckBox checkBox_13, JCheckBox checkBox_14, JCheckBox checkBox_15, JCheckBox checkBox_16, JCheckBox checkBox_17, JCheckBox checkBox_18, JCheckBox checkBox_19, JCheckBox checkBox_20, JCheckBox checkBox_21, JCheckBox checkBox_22, JCheckBox checkBox_23, JCheckBox checkBox_24, JCheckBox checkBox_25, JCheckBox checkBox_26, JCheckBox checkBox_27, JCheckBox checkBox_28, JCheckBox checkBox_29, JCheckBox checkBox_30, JCheckBox checkBox_31, JCheckBox checkBox_32, JCheckBox checkBox_33, JCheckBox checkBox_34, JCheckBox checkBox_35, JCheckBox checkBox_36, JCheckBox checkBox_37, JCheckBox checkBox_38, JCheckBox checkBox_39, JCheckBox checkBox_40, JCheckBox checkBox_41, JCheckBox checkBox_42, JCheckBox checkBox_43, JCheckBox checkBox_44, JCheckBox checkBox_45)
	{
		if(checkBox.isSelected())
		{
			mat.add(checkBox.getText());
		}
		if(checkBox_1.isSelected())
		{
			mat.add(checkBox_1.getText());
		}
		if(checkBox_2.isSelected())
		{
			mat.add(checkBox_2.getText());
		}
		if(checkBox_3.isSelected())
		{
			mat.add(checkBox_3.getText());
		}
		if(checkBox_4.isSelected())
		{
			mat.add(checkBox_4.getText());
		}
		if(checkBox_5.isSelected())
		{
			mat.add(checkBox_5.getText());
		}
		if(checkBox_6.isSelected())
		{
			mat.add(checkBox_6.getText());
		}
		if(checkBox_7.isSelected())
		{
			mat.add(checkBox_7.getText());
		}
		if(checkBox_8.isSelected())
		{
			mat.add(checkBox_8.getText());
		}
		if(checkBox_9.isSelected())
		{
			mat.add(checkBox_9.getText());
		}
		if(checkBox_10.isSelected())
		{
			mat.add(checkBox_10.getText());
		}
		if(checkBox_11.isSelected())
		{
			mat.add(checkBox_11.getText());
		}
		if(checkBox_12.isSelected())
		{
			mat.add(checkBox_12.getText());
		}
		if(checkBox_13.isSelected())
		{
			mat.add(checkBox_13.getText());
		}
		
		if(checkBox_14.isSelected())
		{
			mat.add(checkBox_14.getText());
		}
		if(checkBox_15.isSelected())
		{
			mat.add(checkBox_15.getText());
		}		
		if(checkBox_16.isSelected())
		{
			mat.add(checkBox_16.getText());
		}
		if(checkBox_17.isSelected())
		{
			mat.add(checkBox_17.getText());
		}
		if(checkBox_18.isSelected())
		{
			mat.add(checkBox_18.getText());
		}
		if(checkBox_19.isSelected())
		{
			mat.add(checkBox_19.getText());
		}
		if(checkBox_20.isSelected())
		{
			mat.add(checkBox_20.getText());
		}
		if(checkBox_21.isSelected())
		{
			mat.add(checkBox_21.getText());
		}
		if(checkBox_22.isSelected())
		{
			mat.add(checkBox_22.getText());
		}
		if(checkBox_23.isSelected())
		{
			mat.add(checkBox_23.getText());
		}
		if(checkBox_24.isSelected())
		{
			mat.add(checkBox_24.getText());
		}
		if(checkBox_25.isSelected())
		{
			mat.add(checkBox_25.getText());
		}
		if(checkBox_26.isSelected())
		{
			mat.add(checkBox_26.getText());
		}
		if(checkBox_27.isSelected())
		{
			mat.add(checkBox_27.getText());
		}
		if(checkBox_28.isSelected())
		{
			mat.add(checkBox_28.getText());
		}
		if(checkBox_29.isSelected())
		{
			mat.add(checkBox_29.getText());
		}
		if(checkBox_30.isSelected())
		{
			mat.add(checkBox_30.getText());
		}
		if(checkBox_31.isSelected())
		{
			mat.add(checkBox_31.getText());
		}
		if(checkBox_32.isSelected())
		{
			mat.add(checkBox_32.getText());
		}
		if(checkBox_33.isSelected())
		{
			mat.add(checkBox_33.getText());
		}
		if(checkBox_34.isSelected())
		{
			mat.add(checkBox_34.getText());
		}
		if(checkBox_35.isSelected())
		{
			mat.add(checkBox_35.getText());
		}
		if(checkBox_36.isSelected())
		{
			mat.add(checkBox_36.getText());
		}
		if(checkBox_37.isSelected())
		{
			mat.add(checkBox_37.getText());
		}
		if(checkBox_38.isSelected())
		{
			mat.add(checkBox_38.getText());
		}
		if(checkBox_39.isSelected())
		{
			mat.add(checkBox_39.getText());
		}
		if(checkBox_40.isSelected())
		{
			mat.add(checkBox_40.getText());
		}
		if(checkBox_41.isSelected())
		{
			mat.add(checkBox_41.getText());
		}
		if(checkBox_42.isSelected())
		{
			mat.add(checkBox_42.getText());
		}
		if(checkBox_43.isSelected())
		{
			mat.add(checkBox_43.getText());
		}
		if(checkBox_44.isSelected())
		{
			mat.add(checkBox_44.getText());
		}
		if(checkBox_45.isSelected())
		{
			mat.add(checkBox_45.getText());
		}
		System.out.println(mat);
		setMat(mat);
	}
	public void Check곡물_견과류(JCheckBox checkBox, JCheckBox checkBox_1, JCheckBox checkBox_2, JCheckBox checkBox_3, JCheckBox checkBox_4, JCheckBox checkBox_5, JCheckBox checkBox_6, JCheckBox checkBox_7)
	{
		if(checkBox.isSelected())
		{
			mat.add(checkBox.getText());
		}
		if(checkBox_1.isSelected())
		{
			mat.add(checkBox_1.getText());
		}
		if(checkBox_2.isSelected())
		{
			mat.add(checkBox_2.getText());
		}
		if(checkBox_3.isSelected())
		{
			mat.add(checkBox_3.getText());
		}
		if(checkBox_4.isSelected())
		{
			mat.add(checkBox_4.getText());
		}
		if(checkBox_5.isSelected())
		{
			mat.add(checkBox_5.getText());
		}
		if(checkBox_6.isSelected())
		{
			mat.add(checkBox_6.getText());
		}
		if(checkBox_7.isSelected())
		{
			mat.add(checkBox_7.getText());
		}
		System.out.println(mat);
		setMat(mat);
	}
	public void Check가공_유제품(JCheckBox checkBox, JCheckBox checkBox_1, JCheckBox checkBox_2, JCheckBox checkBox_3, JCheckBox checkBox_4, JCheckBox checkBox_5, JCheckBox checkBox_6, JCheckBox checkBox_7, JCheckBox checkBox_8, JCheckBox checkBox_9, JCheckBox checkBox_10, JCheckBox checkBox_11, JCheckBox checkBox_12, JCheckBox checkBox_13, JCheckBox checkBox_14, JCheckBox checkBox_15, JCheckBox checkBox_16, JCheckBox checkBox_17, JCheckBox checkBox_18, JCheckBox checkBox_19)
	{
		if(checkBox.isSelected())
		{
			mat.add(checkBox.getText());
		}
		if(checkBox_1.isSelected())
		{
			mat.add(checkBox_1.getText());
		}
		if(checkBox_2.isSelected())
		{
			mat.add(checkBox_2.getText());
		}
		if(checkBox_3.isSelected())
		{
			mat.add(checkBox_3.getText());
		}
		if(checkBox_4.isSelected())
		{
			mat.add(checkBox_4.getText());
		}
		if(checkBox_5.isSelected())
		{
			mat.add(checkBox_5.getText());
		}
		if(checkBox_6.isSelected())
		{
			mat.add(checkBox_6.getText());
		}
		if(checkBox_7.isSelected())
		{
			mat.add(checkBox_7.getText());
		}
		if(checkBox_8.isSelected())
		{
			mat.add(checkBox_8.getText());
		}
		if(checkBox_9.isSelected())
		{
			mat.add(checkBox_9.getText());
		}
		if(checkBox_10.isSelected())
		{
			mat.add(checkBox_10.getText());
		}
		if(checkBox_11.isSelected())
		{
			mat.add(checkBox_11.getText());
		}
		if(checkBox_12.isSelected())
		{
			mat.add(checkBox_12.getText());
		}
		if(checkBox_13.isSelected())
		{
			mat.add(checkBox_13.getText());
		}
		
		if(checkBox_14.isSelected())
		{
			mat.add(checkBox_14.getText());
		}
		if(checkBox_15.isSelected())
		{
			mat.add(checkBox_15.getText());
		}		
		if(checkBox_16.isSelected())
		{
			mat.add(checkBox_16.getText());
		}
		if(checkBox_17.isSelected())
		{
			mat.add(checkBox_17.getText());
		}
		if(checkBox_18.isSelected())
		{
			mat.add(checkBox_18.getText());
		}
		if(checkBox_19.isSelected())
		{
			mat.add(checkBox_19.getText());
		}
		System.out.println(mat);
		setMat(mat);
	}
}
